### ISSUE TITLE
Which files are copied to `deno_dist`?

### ISSUE THREAD

**Issue by nebrelbug** [garronej/denoify#11]
This is a really cool project!

Just wondering which files are copied to `deno_dist` when the user runs `denoify`. It looks like `README.md` is... I would also love it if `LICENSE` and `egg.json` or `egg.yml` were copied.

Also, does running `denoify` merge output with the files in `deno_dist` or does it overwrite the whole directory?

Ideally, there would be some option where users could specify which files they wanted copied over.

**Comment by nebrelbug** [comment]
It'd also be great if we could specify files to be excluded from the `deno_dist` directory. If you could point me to some files, I'd be totally willing to take a look at this and create a PR :+1: 

Thanks for the great work!

**Comment by garronej** [comment]
Hi @nebrelbug, thanks for your interest for the project.  


> Just wondering which files are copied to `deno_dist` when the user runs `denoify`. It looks like `README.md` is... I would also love it if `LICENSE` and `egg.json` or `egg.yml` were copied.

I am very glad you asked. There is obviously a needs to copy more than just the `README.md` in the `deno_dist/` directory.
I was hoping someone would raise the issue so I can discuss it with someone. 
My idea was to have an extra custom `package.json` field where you would list files to include. What do you think about that?
I think it is safe to assume that `LICENSE` if present should always be copied in.
Also, I was wondering if it would be feasible to create symbolic links instead of making hard copies but I am afraid it could cause issues in Windows systems.

> Also, does running `denoify` merge output with the files in `deno_dist` or does it overwrite the whole directory?

It merges

> It'd also be great if we could specify files to be excluded from the `deno_dist` directory. If you could point me to some files, I'd be totally willing to take a look at this and create a PR 👍
> 
> Thanks for the great work!

Do you know that you can put `//@denoify-ignore` at the top of any `.ts` or `.tsx` file and it get ignored by Denoify?
Do you know as well that if you have a `foo.deno.ts` and no `foo.ts` somewhere in the source directory `foo.deno.ts` get moved to `foo.ts` in the `deno_dist` directory?  
Would this fit your use-case?

Regards

**Comment by nebrelbug** [comment]
Thanks for the response!

> My idea was to have an extra custom package.json field where you would list files to include

Sounds like a good idea to me. It might be helpful if all the `denoify` fields were under one `"denoify"` parent field in `package.json`. I think if LICENSE is present it can just be copied in.

I think it might be better not to create symbolic links... I feel like those tend to create lots of bugs.

> Do you know that you can put //@denoify-ignore at the top of any .ts or .tsx file and it get ignored by Denoify?

I didn't! Thanks for letting me know.

> Do you know as well that if you have a foo.deno.ts and no foo.ts somewhere in the source directory foo.deno.ts get moved to foo.ts in the deno_dist directory?

Didn't know that either! I'm actually doing this right now with `mod.deno.ts` and it works perfectly, and overwrites the default `mod.ts` that is generated by Denoify. I'm ignoring the `index.ts` file with `//@denoify-ignore`

Thanks again!

**Comment by garronej** [comment]
> It might be helpful if all the `denoify` fields were under one `"denoify"` parent field in `package.json`.

Agreed, that is what I was thinking, it introduces yet another breaking change though, I guess it's OK as we're not stable yet.  

> I think if LICENSE is present it can just be copied in.

Featured in `v0.4.14`  

> I think it might be better not to create symbolic links... I feel like those tend to create lots of bugs.

👍 

> Didn't know that either! I'm actually doing this right now with `mod.deno.ts` and it works perfectly, and overwrites the default `mod.ts` that is generated by Denoify. I'm ignoring the `index.ts` file with `//@denoify-ignore`

Cool! I am thinking about automatically renaming all `index.ts` in `mod.ts` in `deno_dist` to make the produced Deno distribution more "denoish". But I am not sure it is a good ide as I remember Ry saying something like "if you do something just because you think it's cute it is probably a bad idea that you will regret down the line."  
What do you think?

**Comment by garronej** [comment]
Took me some time but:  

**NEW IN v0.5** *Breaking changes*  
-All Denoify parameters are now gathered under a uniq `"denoify"` field.  
-Possibility to specify which files should be copied to the `deno_dist` directory (Previously only `README.md` vas copied).  
[Valid config example](https://github.com/garronej/my_dummy_npm_and_deno_module/blob/master/package.json)

Thanks for the suggestions!

**Comment by nebrelbug** [comment]
@garronej just gave my JS template engine, [Eta](https://deno.land/x/eta), Deno support! Thanks for your great package.

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/92286227-bc869400-ef06-11ea-8f0b-4b56ef936224.png)

**Comment by garronej** [comment]
I don't know if you saw but I added eta in the readme
