### ISSUE TITLE
Accept URL imports

### ISSUE THREAD

**Issue by thgh** [garronej/denoify#7]
I may not be using denoify as intended because I had already replaced soms imports with URLs, so I got this:
```
import ipaddr from "https://jspm.dev/ipaddr.js DENOIFY: DEPENDENCY UNMET (BUILTIN)";
```

**Comment by garronej** [comment]
Hello @thgh 
Could you point me to the repo where you are trying to setup Denoify? 

Otherwise, it is a small issue.

Just leave 

```typescript
import ipaddr from "ipaddr.js"
```
In your `src` files and add this to your `package.json`:

```json
{
  "dependencies": {
    "ipaddr.js": "^1.1.0"
  },
  "denoPorts": {
    "ipaddr.js": "https://raw.githubusercontent.com/whitequark/ipaddr.js/master/lib/ipaddr.js"
  }
}
```

The result should be that when you run ``npx denoify`` the import should be replaced in `deno_dist` by

```typescript
import ipaddr from "https://raw.githubusercontent.com/whitequark/ipaddr.js/v1.1.0/lib/ipaddr.js";
````

( assuming the version of `ipaddr.js` you had installed in your node module is the `1.1.0` at the time when you run `denoify. Denoify will try to find the right version )

Let me know if it works, otherwise I should be able to fix a PR for you. 

Regards

**Comment by garronej** [comment]
And by the way, there is [an update](https://github.com/garronej/denoify/commit/c1d261e3d2474c6767554c1b40304b56d97577c9) coming soon that should bring out of the box support for `ipaddr.js` and many other modules.

**Comment by thgh** [comment]
Cool, I was trying out denoify to port a nodejs project to deno: https://github.com/lithdew/flatend/pull/8
But it's a one time thing so not really what denoify was made for. Still, it would make sense that if you run denoify over a deno codebase that it would not change anything.

**Comment by garronej** [comment]
Ok noted. 👍

**Comment by garronej** [comment]
Done
